// AUTO-GENERATED by scripts/generate-pages.mjs — do not edit by hand.
// Edit src/data/sitemap.ts then run `npm run gen:pages`.
import type { Metadata } from "next";
import PageStub from "@/components/PageStub";
import { getPageByRoute } from "@/data/sitemap";

const page = getPageByRoute("/resources/blog");

export const metadata: Metadata = {
  title: page.label,
  description: page.purpose,
};

export default function Page() {
  return <PageStub page={page} groupId="resources" />;
}
