// GENERATED by scripts/generate-yuniversal.mjs — do not edit by hand.
// Sources: scripts/assets/yuniversal/*.svg (Figma YuniversalCanvas, 2923:67921).

/** Paint order, back to front. `inset` is [top, right, bottom, left] as % of
 * the 1920×1465 hero frame; the image is public/hero/yuniversal/<id>.svg. */
export const yuniversalLayers = [
  {
    "id": "dwarf-stars-1",
    "inset": [
      7.2572,
      -26.6942,
      0.6164,
      -1.7476
    ]
  },
  {
    "id": "dwarf-stars-2",
    "inset": [
      3.9952,
      -17.9749,
      0.3468,
      -12.7904
    ]
  },
  {
    "id": "dwarf-stars-3",
    "inset": [
      20.3299,
      -17.3546,
      6.8557,
      -28.5247
    ]
  },
  {
    "id": "dwarf-stars-4",
    "inset": [
      2.9016,
      -25.2192,
      4.1422,
      -27.2947
    ]
  },
  {
    "id": "dwarf-stars-5",
    "inset": [
      -9.3887,
      7.3317,
      0.7133,
      -28.3902
    ]
  },
  {
    "id": "dwarf-stars-6",
    "inset": [
      24.3405,
      -24.1832,
      10.4033,
      -28.8742
    ]
  },
  {
    "id": "gas-giant",
    "inset": [
      54.283,
      7.8454,
      29.323,
      79.6454
    ]
  },
  {
    "id": "bright-star-a",
    "inset": [
      84.133,
      93.7362,
      -0.407,
      -6.1538
    ]
  },
  {
    "id": "bright-star-b",
    "inset": [
      -0.2581,
      68.0471,
      85.7219,
      20.8571
    ]
  },
  {
    "id": "bright-star-c",
    "inset": [
      76.672,
      13.967,
      6.912,
      73.507
    ]
  },
  {
    "id": "nebula-right",
    "inset": [
      -27.0765,
      -25.3042,
      -109.5265,
      42.8058
    ]
  },
  {
    "id": "nebula-left",
    "inset": [
      -14.9465,
      67.9758,
      -29.3765,
      -33.9242
    ]
  },
  {
    "id": "dwarf-planet",
    "inset": [
      67.2435,
      80.1858,
      27.0435,
      15.4558
    ]
  }
] as const;

export type YuniversalLayerId = (typeof yuniversalLayers)[number]["id"];
