// -----------------------------------------------------------------------------
// Page generator
// -----------------------------------------------------------------------------
// Reads the sitemap (single source of truth) and writes one Next.js App Router
// page per route into src/app. Each page is a thin wrapper that looks its own
// record up from the sitemap data and renders the <PageStub> placeholder.
//
// Run:  npm run gen:pages
//
// Safe to re-run: it only writes the generated stub files listed below and will
// not touch hand-authored pages (see authoredRoutes) or page.tsx (home)
// or sitemap/page.tsx.
// -----------------------------------------------------------------------------
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { navGroups } from "../src/data/sitemap.ts";
import { authoredRoutes } from "../src/data/pages/index.ts";

const authoredRouteSet = new Set(authoredRoutes);

const __dirname = dirname(fileURLToPath(import.meta.url));
const APP_DIR = join(__dirname, "..", "src", "app");

/** Build the list of pages to generate (nav group labels are not routable). */
const targets = [];
for (const group of navGroups) {
  for (const p of group.pages) targets.push({ ...p, groupId: group.id });
}

function fileInfoFor(route) {
  const segments = route.replace(/^\//, "").split("/").filter(Boolean);
  return {
    filePath: join(APP_DIR, ...segments, "page.tsx"),
    displayPath: join("src/app", ...segments, "page.tsx"),
  };
}

function template(route, groupId) {
  return `// AUTO-GENERATED by scripts/generate-pages.mjs — do not edit by hand.
// Edit src/data/sitemap.ts then run \`npm run gen:pages\`.
import type { Metadata } from "next";
import PageStub from "@/components/PageStub";
import { getPageByRoute } from "@/data/sitemap";

const page = getPageByRoute(${JSON.stringify(route)});

export const metadata: Metadata = {
  title: page.label,
  description: page.purpose,
};

export default function Page() {
  return <PageStub page={page} groupId=${JSON.stringify(groupId)} />;
}
`;
}

let count = 0;
let skipped = 0;
for (const t of targets) {
  if (authoredRouteSet.has(t.route)) {
    skipped++;
    console.log(`  ⊘ ${t.route}  (hand-authored — skipped)`);
    continue;
  }
  const { filePath, displayPath } = fileInfoFor(t.route);
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, template(t.route, t.groupId), "utf8");
  count++;
  console.log(`  ✓ ${t.route}  →  ${displayPath}`);
}

console.log(`\nGenerated ${count} page stubs from the sitemap (${skipped} hand-authored pages skipped).`);
